name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 这将匹配所有以 'v' 开头的标签，例如 v1.0.0, v2.1.3 等

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.5  # 使用您的 Go 版本

    - name: Run build script
      run: |
        chmod +x build.sh
        ./build.sh

    - name: List build directory contents
      run: ls -l build/
      shell: bash

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      run: |
        for file in build/*; do
          filename=$(basename "$file")
          echo "Uploading $filename"
          upload_url="${{ steps.create_release.outputs.upload_url }}"
          upload_url="${upload_url%\{*}"  # 移除 URL 末尾的 {?name,label}
          echo "Upload URL: $upload_url?name=$filename"
          curl -X POST \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/octet-stream" \
               --data-binary @"$file" \
               -f \
               "$upload_url?name=$filename"
        done
      shell: bash
